version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-stm-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rqn5p2ntbbrk"
s3_prefix = "aws-stm-sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
