# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  aws-stm-sam-app

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  appDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/appDetails.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      # Environment:
      #   Variables:
      #     dynamodb_table: !Ref steamAppDB
      Events:
        getAppDetails:
          Type: Api
          Properties:
            Path: /appDetails/{appId}
            Method: get
  # steamAppDB:
  #   Type: AWS::Serverless::SimpleTable
  #   PrimaryKey:
  #     Name: id
  #     Type: String
  #   ProvisionedThroughput:
  #     ReadCapacityUnits: 5
  #     WriteCapacityUnits: 5
          
Outputs:
  AddressApi:
    Description: "API Gateway endpoint URL. Returns AppDetails."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/appDetails"